### ISSUE TITLE
[Bug] Broken link on "[Cross Compiler] AVR GCC" wiki page

### ISSUE THREAD

**Issue by per1234** [snowfox-project/snowfox#15]
From https://github.com/snowfox-project/snowfox/wiki/%5BCross-Compiler%5D-AVR-GCC:
>This manual serves to document how to build avr-gcc from source and is based on [salkinium/docker-avr-gcc](https://github.com/salkinium/docker-avr-gcc-7/blob/master/build.sh).

The "salkinium/docker-avr-gcc" link gives a 404 error. I don't see any equivalent under salkinium's repos, so it was either deleted or made private.

I can access it via the Wayback Machine:
http://web.archive.org/web/20180617164424/https://github.com/salkinium/docker-avr-gcc-7

**Comment by aentinger** [comment]
Thank you @per1234 for finding this one :wink: The repository was moved here ... https://github.com/modm-ext/docker-avr-gcc . I've given you write access in case you want to fix this ;)

**Comment by per1234** [comment]
Fixed by https://github.com/snowfox-project/snowfox/wiki/%5BCross-Compiler%5D-AVR-GCC/_compare/8afdf6cf269d67d5743148106288507156cacaf6...7ce23571f7ad448f3adb165fcd60865b06ea61ab
